### create competition
POST http://localhost:8080/api/v1/competitions
content-type: application/json

{
  "name": "competition42",
  "date": "0002-01-01T00:00:00Z",
  "rank": 1,
  "won_competition": true,
  "student_id": "639487bde900f99197853a1b"
}

### get competition by id
GET http://localhost:8080/api/v1/competitions/63bab57e9e34f18dafb33e4b

###

# get all competitions
GET http://localhost:8080/api/v1/competitions/

### update competition by id
PATCH http://localhost:8080/api/v1/competitions/63bab57e9e34f18dafb33e4b
content-type: application/json

{
  "name": "name of the competition 42"
}

### delete competition by id
DELETE http://localhost:8080/api/v1/competitions/63bab57e9e34f18dafb33e4b 
content-type: application/json