### create daily-note
POST http://localhost:8080/api/v1/daily-notes
content-type: application/json

{
  "student_id": "639487bde900f99197853a1b",
  "created_at" : "0002-01-01T00:00:00Z",
  "subject" : "639487bde900f99197853a1b",
  "rating": 2,
  "note": "this is a note",
  "creator_id": "639487bde900f99197853a1b",
  "updated_at":  "0002-01-01T00:00:00Z"
}

### get daily-note by id
GET http://localhost:8080/api/v1/daily-notes/63a4c424d799116cf36b36b7

###

# get all daily-notes
GET http://localhost:8080/api/v1/daily-notes/

### update daily-note by id
PATCH http://localhost:8080/api/v1/daily-notes/63a4c424d799116cf36b36b7
content-type: application/json

{
 "rating" : 4
}

### delete daily-note by id
DELETE http://localhost:8080/api/v1/daily-notes/63a4c424d799116cf36b36b7 
content-type: application/json