### create parent
POST http://localhost:8080/api/v1/parents/
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "address": {
    "street": "ulf",
    "zip": 1,
    "house_no": 1,
    "city": "ulf"
  },
  "phone": "ulf",
  "email": "ulf",
  "children" : ["639487bde900f99197853a1b"]

}

### get parent by id
GET http://localhost:8080/api/v1/parents/63a4c4ee11fba69c2364381e

###

# get all parent
GET http://localhost:8080/api/v1/parents/

### update parent by id
PATCH http://localhost:8080/api/v1/parents/63a4c4ee11fba69c2364381e
content-type: application/json

{
  "email": "NEW MAIL",
   "address": {
    "street": "NEW STREET"
  }
}

### delete parent by id
DELETE http://localhost:8080/api/v1/parents/63a4c4ee11fba69c2364381e 
content-type: application/json