### create student
POST http://localhost:8080/api/v1/student/create
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "class_teacher": "ulf",
  "birthday": "0002-01-01T00:00:00Z",
  "gender": "ulf",
  "address": {
    "street": "ulf",
    "zip": 1,
    "house_no": 1,
    "city": "ulf"
  },
  "phone": "ulf",
  "email": "ulf",
  "social_media": "ulf",
  "certificate": ["ulf"]

}

### get student by id
GET http://localhost:8080/api/v1/student/get/638b58e74cda3d69dc111976

###

# get all students
GET http://localhost:8080/api/v1/student/all

### update student by id
PATCH http://localhost:8080/api/v1/student/update/638b58e74cda3d69dc111976
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "class_teacher": "ulf 2.0",
  "birthday": "0002-01-01T00:00:00Z",
  "gender": "ulf",
  "address": {
    "street": "ulf",
    "zip": 1,
    "house_no": 1,
    "city": "ulf"
  },
  "phone": "ulf",
  "email": "ulf",
  "social_media": "ulf",
  "certificate": ["ulf"]

}

### delete student by id
DELETE http://localhost:8080/api/v1/student/delete/638b58e74cda3d69dc111976 
content-type: application/json