### create student
POST http://localhost:8080/api/v1/students/
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "class_teacher": "ulf",
  "birthday": "0002-01-01T00:00:00Z",
  "gender": "ulf",
  "address": {
    "street": "ulf",
    "zip": 1,
    "house_no": 1,
    "city": "ulf"
  },
  "phone": "ulf",
  "email": "ulf",
  "social_media": "ulf",
  "certificate": ["ulf"]
}

### get student by id
GET http://localhost:8080/api/v1/students/63bacf65c1a2bb9f202f9827

###

# get all students
GET http://localhost:8080/api/v1/students/

### update student by id
PATCH http://localhost:8080/api/v1/students/63bacd85fb8fa7de1cb5b077
content-type: application/json

{
  "email": "NEW MAIL",
  "address": {
    "street": "NEW STREET"
  }
} 

### delete student by id
DELETE http://localhost:8080/api/v1/students/63bacd85fb8fa7de1cb5b077 
content-type: application/json