### create subject
POST http://localhost:8080/api/v1/subjects/
content-type: application/json

{
  "name": "ulf",
  "teacher":  "6392336d2d3dbf230d1f3f03",
  "school_id": "6392336d2d3dbf230d1f3f03",
  "student_ids": ["6392336d2d3dbf230d1f3f03"]

}

### get subject by id
GET http://localhost:8080/api/v1/subjects/63a4c8ce4a3f5b55f5e5006a

###

# get all subjects
GET http://localhost:8080/api/v1/subjects/

### update subject by id
PATCH http://localhost:8080/api/v1/subjects/63a4c8ce4a3f5b55f5e5006a
content-type: application/json

{
  "name": "ulf42"
}

### delete subject by id
DELETE http://localhost:8080/api/v1/subjects/63a4c8ce4a3f5b55f5e5006a 
content-type: application/json