### create subject-grade
POST http://localhost:8080/api/v1/subject-grades/
content-type: application/json

{
  "grade": 3,
  "intermediate_grade": false,
  "student_id": ["6392336d2d3dbf230d1f3f03"]

}

### get subject-grade by id
GET http://localhost:8080/api/v1/subject-grades/63a4c8304a3f5b55f5e50069

###

# get all subject-grades
GET http://localhost:8080/api/v1/subject-grades/

### update subject-grade by id
PATCH http://localhost:8080/api/v1/subject-grades/63a4c8304a3f5b55f5e50069
content-type: application/json

{
  "grade": 1
}

### delete subject-grade by id
DELETE http://localhost:8080/api/v1/subject-grades/63a4c8304a3f5b55f5e50069 
content-type: application/json