### create teacher
POST http://localhost:8080/api/v1/teachers/
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "school": ["6392336d2d3dbf230d1f3f03"],
  "email": "ulf",
  "phone": "ulf"
}

### get teacher by id
GET http://localhost:8080/api/v1/teachers/63a4c91c4a3f5b55f5e5006b

###

# get all teachers
GET http://localhost:8080/api/v1/teachers/

### update teacher by id
PATCH http://localhost:8080/api/v1/teachers/63a4c91c4a3f5b55f5e5006b
content-type: application/json

{
  "email": "ulf42"
}

### delete teacher by id
DELETE http://localhost:8080/api/v1/teachers/63a4c91c4a3f5b55f5e5006b 
content-type: application/json