### create trainer
POST http://localhost:8080/api/v1/trainers/
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "student_ids": ["6392336d2d3dbf230d1f3f03"],
  "sport": ["6392336d2d3dbf230d1f3f03"]
}

### get trainer by id
GET http://localhost:8080/api/v1/trainers/63a4c93c4a3f5b55f5e5006c

###

# get all trainers
GET http://localhost:8080/api/v1/trainers/

### update trainer by id
PATCH http://localhost:8080/api/v1/trainers/63a4c93c4a3f5b55f5e5006c
content-type: application/json

{
  "last_name": "ulf42"
}

### delete trainer by id
DELETE http://localhost:8080/api/v1/trainers/63a4c93c4a3f5b55f5e5006c 
content-type: application/json