### create tutor
POST http://localhost:8080/api/v1/tutors/
content-type: application/json

{
  "first_name": "ulf",
  "last_name": "ulf",
  "email": "ulf",
  "phone": "ulf",
  "subjects":  ["6392336d2d3dbf230d1f3f03"],
  "students": ["6392336d2d3dbf230d1f3f03"]


}

### get tutor by id
GET http://localhost:8080/api/v1/tutors/63baecea771b13ff8283a016

###

# get all tutors
GET http://localhost:8080/api/v1/tutors/

### update tutor by id
PATCH http://localhost:8080/api/v1/tutors/63baecea771b13ff8283a016
content-type: application/json

{
  "email": "ulf42"
}

### delete tutor by id
DELETE http://localhost:8080/api/v1/tutors/63baec24771b13ff8283a015 
content-type: application/json