// Code generated by go-enum DO NOT EDIT.
// Version: 0.3.11
// Revision: e477e74e05be2411bb0b218a4637de6905e8cd8c
// Build Date: 2022-02-11T00:05:30Z
// Built By: goreleaser

package models

import (
	"fmt"
)

const (
	// UserStatusParent is a UserStatus of type Parent.
	UserStatusParent UserStatus = iota
	// UserStatusStudent is a UserStatus of type Student.
	UserStatusStudent
	// UserStatusFaridsTeacher is a UserStatus of type FaridsTeacher.
	UserStatusFaridsTeacher
	// UserStatusTrainer is a UserStatus of type Trainer.
	UserStatusTrainer
	// UserStatusSchoolTeacher is a UserStatus of type SchoolTeacher.
	UserStatusSchoolTeacher
	// UserStatusSuperAdmin is a UserStatus of type SuperAdmin.
	UserStatusSuperAdmin
)

const _UserStatusName = "parentstudentfaridsTeachertrainerschoolTeachersuperAdmin"

var _UserStatusMap = map[UserStatus]string{
	UserStatusParent:        _UserStatusName[0:6],
	UserStatusStudent:       _UserStatusName[6:13],
	UserStatusFaridsTeacher: _UserStatusName[13:26],
	UserStatusTrainer:       _UserStatusName[26:33],
	UserStatusSchoolTeacher: _UserStatusName[33:46],
	UserStatusSuperAdmin:    _UserStatusName[46:56],
}

// String implements the Stringer interface.
func (x UserStatus) String() string {
	if str, ok := _UserStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("UserStatus(%d)", x)
}

var _UserStatusValue = map[string]UserStatus{
	_UserStatusName[0:6]:   UserStatusParent,
	_UserStatusName[6:13]:  UserStatusStudent,
	_UserStatusName[13:26]: UserStatusFaridsTeacher,
	_UserStatusName[26:33]: UserStatusTrainer,
	_UserStatusName[33:46]: UserStatusSchoolTeacher,
	_UserStatusName[46:56]: UserStatusSuperAdmin,
}

// ParseUserStatus attempts to convert a string to a UserStatus.
func ParseUserStatus(name string) (UserStatus, error) {
	if x, ok := _UserStatusValue[name]; ok {
		return x, nil
	}
	return UserStatus(0), fmt.Errorf("%s is not a valid UserStatus", name)
}
